# ─────────────────────────────────────────────────────────────
# Demo Dockerfile — Test Workflow / Infisical Secret Manager
# ─────────────────────────────────────────────────────────────

# Build arguments injected by the GitHub Actions workflow
ARG APP_ENV=dev
ARG GIT_SHA=local

# ── Base image ───────────────────────────────────────────────
FROM node:20-alpine AS base
LABEL maintainer="PearlThoughts"
LABEL org.opencontainers.image.description="Test Workflow App — Infisical Secret Manager Demo"

WORKDIR /app

# ── Install dependencies ──────────────────────────────────────
COPY package*.json ./
RUN npm ci --omit=dev

# ── Copy application source ───────────────────────────────────
COPY server.js .

# ── Copy .env generated by fetch-infisical-env.sh ────────────
#   This file is written by the CI pipeline BEFORE docker build.
#   It contains APIkey and password fetched from Infisical.
COPY .env .env

# ── Build-time metadata ───────────────────────────────────────
ARG APP_ENV
ARG GIT_SHA
ENV APP_ENV=${APP_ENV}
ENV GIT_SHA=${GIT_SHA}

EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
  CMD wget -qO- http://localhost:3000/health || exit 1

CMD ["node", "server.js"]
